name: portfolio
description: Portfolio developed in flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flex_color_scheme: ^7.3.1
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.5.0
  riverpod_annotation: ^2.1.5
  hooks_riverpod: ^2.4.0
  flutter_hooks: ^0.20.1
  collection: ^1.17.2
  url_launcher: ^6.1.14
  firebase_core: ^2.15.1 
  firebase_core_desktop: ^1.0.2
  url_strategy: ^0.2.0
  intl: ^0.18.1
  easy_localization: ^3.0.3
  easy_logger: ^0.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.1
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  custom_lint: ^0.5.3
  riverpod_lint: ^2.0.4
  riverpod_generator: ^2.3.2
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/fonts/

